# Default+ palette for zsh
#
# Generated by bin/build.py from palette.yaml — do not edit by hand.
#
# Source this file from your ~/.zshrc:
#   source ~/Developer/default-plus/zsh/default-plus.zsh

# `ls` colours. LS_COLORS drives GNU ls, eza and zsh completion; LSCOLORS is the
# 8-slot BSD fallback that only /bin/ls reads. They are kept in agreement — the
# two used to disagree on the directory colour.
export CLICOLOR=YES
export LSCOLORS="GxDxFxfxBxEgEdAbAgAcAd"
export LS_COLORS="di=1;38;2;53;176;216:ln=38;2;255;231;109:so=38;2;242;36;140:pi=38;2;242;36;140:ex=1;38;2;252;70;81:bd=38;2;53;176;216;48;2;23;23;23:cd=38;2;53;176;216;48;2;23;23;23:su=38;2;23;23;23;48;2;252;70;81:sg=38;2;23;23;23;48;2;255;231;109:tw=38;2;23;23;23;48;2;86;208;179:ow=38;2;23;23;23;48;2;255;231;109"

# Completion list colours (reuses LS_COLORS above)
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*:descriptions' format '%F{#56D0B3}-- %d --%f'

# VCS / prompt colours
zstyle ':vcs_info:git:*' formats '%F{#FFE76D}%b%f '

setopt PROMPT_SUBST
PROMPT=$'%F{#56D0B3}%~%f ${vcs_info_msg_0_}\n%F{#8E8E8E}$%f '
